"""
Document Generation Service
- Word documents (.docx)
- PowerPoint presentations (.pptx)
- Assignment documents
"""
from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor as PPTRGBColor
from pptx.enum.text import PP_ALIGN
import os
import re
import logging
from datetime import datetime
from typing import Optional, List, Dict

logger = logging.getLogger(__name__)

EXPORTS_DIR = "./exports"
os.makedirs(EXPORTS_DIR, exist_ok=True)


class WordDocumentService:
    """Generate professional Word documents"""
    
    def create_legal_paper(self, title: str, content: str, author: str = "LegalAI") -> str:
        """Create a professional legal paper in Word format"""
        doc = DocxDocument()
        
        # Page margins
        from docx.shared import Cm
        section = doc.sections[0]
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3)
        section.right_margin = Cm(2.5)
        
        # Title
        title_para = doc.add_heading(title, 0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.runs[0]
        title_run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x6e)
        
        # Author and date
        author_para = doc.add_paragraph()
        author_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        author_run = author_para.add_run(f"Prepared by: {author}")
        author_run.font.size = Pt(11)
        author_run.font.italic = True
        
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(f"Date: {datetime.now().strftime('%B %d, %Y')}")
        date_run.font.size = Pt(10)
        date_run.font.italic = True
        
        doc.add_paragraph()  # Spacer
        
        # Add horizontal rule
        doc.add_heading("", level=1)
        
        # Parse and add content
        self._add_content_to_doc(doc, content)
        
        # Footer
        doc.add_paragraph()
        footer_para = doc.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_run = footer_para.add_run("─" * 50 + "\nGenerated by LegalAI | Educational Purposes Only")
        footer_run.font.size = Pt(9)
        footer_run.font.italic = True
        footer_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
        
        # Save
        filename = f"legal_paper_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
        filepath = os.path.join(EXPORTS_DIR, filename)
        doc.save(filepath)
        logger.info(f"Legal paper saved: {filepath}")
        return filepath
    
    def create_assignment(self, title: str, content: str, subject: str = "", 
                          word_count: int = 0, author: str = "Student") -> str:
        """Create an assignment document"""
        doc = DocxDocument()
        
        from docx.shared import Cm
        section = doc.sections[0]
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3)
        section.right_margin = Cm(2.5)
        
        # Header info
        header_table = doc.add_table(rows=1, cols=2)
        header_table.style = 'Table Grid'
        
        left_cell = header_table.cell(0, 0)
        left_cell.text = f"Student: {author}\nSubject: {subject or title}"
        
        right_cell = header_table.cell(0, 1)
        right_cell.text = f"Date: {datetime.now().strftime('%d/%m/%Y')}\nWord Count: ~{word_count or 'N/A'}"
        
        doc.add_paragraph()
        
        # Title
        title_para = doc.add_heading(title, 1)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph()
        
        # Content
        self._add_content_to_doc(doc, content)
        
        # Word count footer
        actual_words = len(content.split())
        footer_para = doc.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        footer_run = footer_para.add_run(f"Total Words: {actual_words}")
        footer_run.font.size = Pt(10)
        footer_run.font.italic = True
        
        filename = f"assignment_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
        filepath = os.path.join(EXPORTS_DIR, filename)
        doc.save(filepath)
        return filepath
    
    def create_test_paper(self, title: str, content: str, subject: str = "") -> str:
        """Create a test paper document"""
        doc = DocxDocument()
        
        from docx.shared import Cm
        section = doc.sections[0]
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)
        
        # Header
        header_para = doc.add_heading(f"EXAMINATION PAPER", 1)
        header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        subject_para = doc.add_heading(title, 2)
        subject_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph()
        
        self._add_content_to_doc(doc, content)
        
        filename = f"test_paper_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
        filepath = os.path.join(EXPORTS_DIR, filename)
        doc.save(filepath)
        return filepath
    
    def _add_content_to_doc(self, doc: DocxDocument, content: str):
        """Parse markdown-like content and add to document"""
        lines = content.split('\n')
        
        for line in lines:
            line = line.rstrip()
            
            if not line:
                doc.add_paragraph()
                continue
            
            # Headings
            if line.startswith('# '):
                p = doc.add_heading(line[2:], 1)
                p.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x6e) if p.runs else None
            elif line.startswith('## '):
                doc.add_heading(line[3:], 2)
            elif line.startswith('### '):
                doc.add_heading(line[4:], 3)
            elif line.startswith('#### '):
                doc.add_heading(line[5:], 4)
            # Bold
            elif line.startswith('**') and line.endswith('**'):
                p = doc.add_paragraph()
                run = p.add_run(line.strip('**'))
                run.bold = True
            # Bullet points
            elif line.startswith('- ') or line.startswith('• '):
                p = doc.add_paragraph(line[2:], style='List Bullet')
            elif re.match(r'^\d+\.', line):
                p = doc.add_paragraph(re.sub(r'^\d+\.\s*', '', line), style='List Number')
            # Normal text with bold inline
            else:
                p = doc.add_paragraph()
                p.paragraph_format.space_after = Pt(6)
                
                # Handle inline bold
                parts = re.split(r'(\*\*.*?\*\*)', line)
                for part in parts:
                    if part.startswith('**') and part.endswith('**'):
                        run = p.add_run(part.strip('**'))
                        run.bold = True
                    else:
                        if part:
                            run = p.add_run(part)
                            run.font.size = Pt(11)


class PPTService:
    """Generate PowerPoint presentations"""
    
    # Professional color themes
    THEMES = {
        "legal_blue": {
            "bg": PPTRGBColor(0x1a, 0x1a, 0x6e),
            "accent": PPTRGBColor(0xC0, 0x96, 0x20),
            "text": PPTRGBColor(0xFF, 0xFF, 0xFF),
            "body_text": PPTRGBColor(0x33, 0x33, 0x33),
            "body_bg": PPTRGBColor(0xF5, 0xF5, 0xF5),
        },
        "professional": {
            "bg": PPTRGBColor(0x2C, 0x3E, 0x50),
            "accent": PPTRGBColor(0xE7, 0x4C, 0x3C),
            "text": PPTRGBColor(0xFF, 0xFF, 0xFF),
            "body_text": PPTRGBColor(0x2C, 0x3E, 0x50),
            "body_bg": PPTRGBColor(0xEC, 0xF0, 0xF1),
        }
    }
    
    def create_presentation(self, ppt_data: dict, theme: str = "legal_blue") -> str:
        """Create a professional PPT presentation"""
        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)
        
        colors = self.THEMES.get(theme, self.THEMES["legal_blue"])
        
        # Title slide
        self._add_title_slide(prs, ppt_data, colors)
        
        # Content slides
        for slide_data in ppt_data.get("slides", []):
            self._add_content_slide(prs, slide_data, colors)
        
        # Thank you / Q&A slide
        self._add_end_slide(prs, colors)
        
        filename = f"presentation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(EXPORTS_DIR, filename)
        prs.save(filepath)
        logger.info(f"Presentation saved: {filepath}")
        return filepath
    
    def _add_title_slide(self, prs: Presentation, data: dict, colors: dict):
        slide_layout = prs.slide_layouts[6]  # Blank
        slide = prs.slides.add_slide(slide_layout)
        
        # Background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = colors["bg"]
        
        # Title box
        title_box = slide.shapes.add_textbox(
            Inches(1), Inches(2), Inches(11.33), Inches(2)
        )
        tf = title_box.text_frame
        tf.word_wrap = True
        p = tf.add_paragraph()
        p.text = data.get("topic", "Legal Presentation")
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = colors["text"]
        p.alignment = PP_ALIGN.CENTER
        
        # Subtitle
        sub_box = slide.shapes.add_textbox(
            Inches(1), Inches(4.2), Inches(11.33), Inches(0.8)
        )
        tf2 = sub_box.text_frame
        p2 = tf2.add_paragraph()
        p2.text = f"Duration: {data.get('duration_minutes', 15)} Minutes | {data.get('slide_count', 10)} Slides"
        p2.font.size = Pt(18)
        p2.font.color.rgb = colors["accent"]
        p2.alignment = PP_ALIGN.CENTER
        
        # Date
        date_box = slide.shapes.add_textbox(
            Inches(1), Inches(5.2), Inches(11.33), Inches(0.5)
        )
        tf3 = date_box.text_frame
        p3 = tf3.add_paragraph()
        p3.text = f"Generated by LegalAI | {datetime.now().strftime('%B %Y')}"
        p3.font.size = Pt(14)
        p3.font.italic = True
        p3.font.color.rgb = PPTRGBColor(0xAA, 0xAA, 0xCC)
        p3.alignment = PP_ALIGN.CENTER
        
        # Decorative line
        from pptx.util import Pt as PtUtil
        line = slide.shapes.add_shape(
            1,  # MSO_SHAPE_TYPE.LINE
            Inches(2), Inches(5.0), Inches(9.33), Inches(0)
        )
    
    def _add_content_slide(self, prs: Presentation, slide_data: dict, colors: dict):
        slide_layout = prs.slide_layouts[6]  # Blank
        slide = prs.slides.add_slide(slide_layout)
        
        # Light background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = colors["body_bg"]
        
        # Title bar
        title_shape = slide.shapes.add_textbox(
            Inches(0), Inches(0), Inches(13.33), Inches(1.2)
        )
        title_fill = title_shape.fill
        title_fill.solid()
        title_fill.fore_color.rgb = colors["bg"]
        
        tf = title_shape.text_frame
        tf.word_wrap = True
        p = tf.add_paragraph()
        p.text = slide_data.get("title", "")
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = colors["text"]
        p.space_before = Pt(10)
        
        # Slide number
        num_box = slide.shapes.add_textbox(
            Inches(12), Inches(0.2), Inches(1), Inches(0.7)
        )
        tf_num = num_box.text_frame
        p_num = tf_num.add_paragraph()
        p_num.text = str(slide_data.get("slide_number", ""))
        p_num.font.size = Pt(20)
        p_num.font.color.rgb = colors["accent"]
        p_num.alignment = PP_ALIGN.RIGHT
        
        # Bullet points
        bullets = slide_data.get("bullets", [])
        if bullets:
            content_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.5), Inches(8), Inches(5.5)
            )
            tf_content = content_box.text_frame
            tf_content.word_wrap = True
            
            for i, bullet in enumerate(bullets[:6]):  # Max 6 bullets
                p_bullet = tf_content.add_paragraph()
                p_bullet.text = f"▸  {bullet}"
                p_bullet.font.size = Pt(18)
                p_bullet.font.color.rgb = colors["body_text"]
                p_bullet.space_before = Pt(8)
        
        # Notes box (script)
        script = slide_data.get("script", "")
        if script:
            notes_slide = slide.notes_slide
            notes_tf = notes_slide.notes_text_frame
            notes_tf.text = f"SCRIPT:\n{script}\n\nNOTES:\n{slide_data.get('notes', '')}"
        
        # Side accent bar
        accent_bar = slide.shapes.add_shape(
            1, Inches(0), Inches(1.2), Inches(0.08), Inches(6.3)
        )
        accent_bar.fill.solid()
        accent_bar.fill.fore_color.rgb = colors["accent"]
        accent_bar.line.fill.background()
    
    def _add_end_slide(self, prs: Presentation, colors: dict):
        slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(slide_layout)
        
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = colors["bg"]
        
        text_box = slide.shapes.add_textbox(
            Inches(2), Inches(2.5), Inches(9), Inches(2)
        )
        tf = text_box.text_frame
        p = tf.add_paragraph()
        p.text = "Thank You"
        p.font.size = Pt(54)
        p.font.bold = True
        p.font.color.rgb = colors["text"]
        p.alignment = PP_ALIGN.CENTER
        
        sub_box = slide.shapes.add_textbox(
            Inches(2), Inches(5), Inches(9), Inches(1)
        )
        tf2 = sub_box.text_frame
        p2 = tf2.add_paragraph()
        p2.text = "Questions & Discussion | Generated by LegalAI"
        p2.font.size = Pt(18)
        p2.font.color.rgb = colors["accent"]
        p2.alignment = PP_ALIGN.CENTER


# Singletons
word_service = WordDocumentService()
ppt_service = PPTService()
